### ISSUE TITLE
Can't disable Operate connectivity for the self-hosted connector runtime 8.2 by following the docs.

### ISSUE THREAD

**Issue by Evil-Crab** [camunda/camunda-platform-docs#2001]
These settings seem to be broken in spring-zeebe 8.2.0.

https://github.com/camunda/camunda-platform-docs/blob/e2bab2166b0b965c708f64cfd55e49d15f54c127/versioned_docs/version-8.2/self-managed/connectors-deployment/connectors-configuration.md?plain=1#L60

After upgrade from 8.1.16 to 8.2.0 application fails to start with a following error:

`2023-04-20 19:08:27.912 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'camundaOperateClient' defined in class path resource [io/camunda/zeebe/spring/client/configuration/OperateClientProdAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.operate.CamundaOperateClient]: Factory method 'camundaOperateClient' threw exception; nested exception is java.lang.IllegalArgumentException: In order to connect to Camunda Operate you need to specify either a SaaS clusterId or an Operate URL.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at io.camunda.connector.runtime.ConnectorRuntimeApplication.main(ConnectorRuntimeApplication.java:28)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.operate.CamundaOperateClient]: Factory method 'camundaOperateClient' threw exception; nested exception is java.lang.IllegalArgumentException: In order to connect to Camunda Operate you need to specify either a SaaS clusterId or an Operate URL.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 18 common frames omitted
Caused by: java.lang.IllegalArgumentException: In order to connect to Camunda Operate you need to specify either a SaaS clusterId or an Operate URL.
	at io.camunda.zeebe.spring.client.properties.OperateClientConfigurationProperties.getOperateUrl(OperateClientConfigurationProperties.java:83)
	at io.camunda.zeebe.spring.client.configuration.OperateClientProdAutoConfiguration.camundaOperateClient(OperateClientProdAutoConfiguration.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 19 common frames omitted`

**Comment by akeller** [comment]
Hi there! Thanks for reporting this. I've contacted the Connectors team internally to see if we can triage this.

**Comment by igpetrov** [comment]
Hi folks! Thank you for reporting! I am taking a look at the issue.

@Evil-Crab, for the time being, please use additional environment variable `OPERATE_CLIENT_ENABLED=false`.

Current relevant execution from JAR bundle:

```
java -cp 'bundle.jar' -Dserver.port=9898 -Dzeebe.client.broker.gateway-address=127.0.0.1:26500 -Dzeebe.client.security.plaintext=true -Dcamunda.connector.polling.enabled=false -Dcamunda.connector.webhook.enabled=false -Doperate.client.enabled=false -Dspring.main.web-application-type=none io.camunda.connector.runtime.ConnectorRuntimeApplication
```

Please let us know if you have any questions.

**Comment by igpetrov** [comment]
Changes are here: https://github.com/camunda/camunda-platform-docs/pull/2009
